boulder:
    build: .
    dockerfile: Dockerfile
    net: bridge
    ports:
      - 4000:4000
      - 4002:4002
      - 4003:4003
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
    links:
      - bmysql:boulder-mysql
      - brabbitmq:boulder-rabbitmq
    extra_hosts:
      - boulder:127.0.0.1
    environment:
        FAKE_DNS: 172.17.0.1
bmysql:
    image: mariadb:10.0
    net: bridge
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --bind-address=0.0.0.0
    log_driver: none
brabbitmq:
    image: rabbitmq:3
    net: bridge
    environment:
        RABBITMQ_NODE_IP_ADDRESS: "0.0.0.0"
    log_driver: none
